name = "UnifiedMetrics"
uuid = "2f5f7d54-6893-4422-9ad5-7bdbd4c94e46"
authors = ["Resul Akay <resul.akay@taf-society.org> and contributors"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
